altinn.tre.base.url=https://platform.altinn.no
altinn.tre.token.exchange.path=https://platform.altinn.no/authentication/api/v1/exchange/maskinporten
altinn.tre.inntektsmelding.ressurs=nav_sykdom-i-familien_inntektsmelding

k9inntektsmelding.scopes=api://prod-gcp.k9saksbehandling.k9-inntektsmelding/.default
k9inntektsmelding.url=https://k9-inntektsmelding.intern.nav.no/k9/inntektsmelding
