kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: k9-inntektsmelding-api
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /internal/health/isAlive
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  readiness:
    path: /internal/health/isReady
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  preStopHook:
    http:
      path: /internal/health/preStop
  prometheus:
    enabled: true
    path: /internal/metrics/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
      scaleUpStabilizationWindowSeconds: 30
  resources:
    limits:
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          atMaxAge: 600
          enabled: true
          product: inntektsmelding
          separator: "/"
          name: k9
      consumes:
        - name: "altinn:authorization/authorize"
  azure:
    application:
      enabled: true
  envFrom:
    - secret: k9-inntektsmelding-api
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: k9-inntektsmelding
      external:
      {{#if devOnly}}
        - host: platform.tt02.altinn.no
      {{else}}
        - host: platform.altinn.no
      {{/if}}
