name: Bygg og deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'lokalutvikling/**'
      - '.github/*.yml'

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-build-app.yml@main
    with:
      java-version: 25
      build-image: true
      push-image: ${{ github.ref_name == github.event.repository.default_branch}}
    secrets: inherit
